replicaCount: 1

image:
  repository: nginx
  tag: "1.21.6"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "alb"
  annotations: {}
  host: web.beomj.link
  path: /
  pathType: Prefix
  tls: []
  # - secretName: web-tls
  #   hosts:
  #     - web.beomj.link

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}